# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "みんなの地図"
description: > # this means to ignore newlines until "email:"
   西日本豪雨に被害に遭われた方にお見舞い申し上げます。<br>
   みんなの地図は、被災された方、また復旧に向けて頑張っておられる方を
   後方支援するため、突貫で作成したアプリです。<br>


email: a-mail@mail.mail
#blog logo
logo: "/assets/images/map_family_smile.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/map_family_smile.png"

name: 'みんなの地図'
author: ""
author_image: "/assets/images/map_family_smile.png"

paginate:	5

url: "https://daichancorgi.github.io/minchizu-lp/"
baseurl: ""
#used to display twitter cards
twitter_handle: '@minnanochizu'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/minnanochizu
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
